name: Deploy static site to GitHub Pages

on:
  push:
    branches:
      - main  # Branche qui déclenche le déploiement

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v7
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Modifie si ton site est dans docs/
